# Project information
site_name: Ionide Documentation
site_description: Documentation for Ionide
site_author: Krzysztof Cieslak
site_url: http://ionide.io/docs/

# Repository
repo_name: Ionide/docs
repo_url: https://github.com/Ionide/docs
theme:
  name: 'material'
  custom_dir: 'theme'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/Ionide'
    - type: 'twitter'
      link: 'https://twitter.com/IonideProject'
    - type: globe
      link: http://ionide.io

pages:
- Home: 'index.md'
- User Guide:
  - 'Editing evolved': 'editing.md'
  - 'Project managment': 'project.md'
  - 'Debugging': 'debugger.md'
  - 'Testing': 'testing.md'
  - 'Paket integration': 'paket.md'
  - 'FAKE integration': 'fake.md'
- Reference:
  - 'List of commands': 'commands.md'
  - 'List of options': 'options.md'
- Advanced:
  - 'Architecture': 'architecture.md'
  - 'How to contribute': 'how-to-contribute.md'